/* Traducciones de la pagina de CV. Mismo formato que i18n-data.js: el espanol
   esta en cv.html y i18n.js lo copia del DOM; aca va el ingles y la unica
   cadena en espanol que no aparece en la pagina. */
window.PF_TRANSLATIONS = {
  "es": {
    "lang_aria": "Switch to English"
  },
  "en": {
    "lang_aria": "Cambiar a español",
    "cv_back": "← Portfolio",
    "cv_pdf": "Download PDF",
    "cv_role": "Software Developer · Linux · IT Infrastructure · Support",
    "cv_loc": "Rosario, Santa Fe, Argentina",
    "cv_avail": "Full time · on-site, hybrid or remote",
    "cv_profile_title": "Profile",
    "cv_profile_text": "Software developer in the final year of a technical degree. I build, deploy and run my own web applications in production: Python and PostgreSQL backends, Next.js frontends and the Linux infrastructure they run on (Ubuntu on AWS EC2, Docker, reverse proxy with HTTPS, backups). I apply security to what I build and troubleshoot failures from logs. Certified in Linux Essentials and currently taking Network Technician, both from Cisco.",
    "cv_skills_title": "Technical skills",
    "cv_s1_k": "Linux systems",
    "cv_s1_v": "Ubuntu Server · SSH · Bash · apt · systemd · journalctl · users and permissions · services · UFW · backups",
    "cv_s2_k": "Cloud / DevOps",
    "cv_s2_v": "AWS EC2 · Docker · Docker Compose · Git and GitHub · deployments with migrations (Alembic)",
    "cv_s3_k": "Networking",
    "cv_s3_v": "TCP/IP · DNS · HTTP/HTTPS · TLS · reverse proxy (Caddy) · Cloudflare",
    "cv_s4_k": "Security",
    "cv_s4_v": "JWT · OAuth 2.0 · roles and permissions · bcrypt · HttpOnly cookies · CSP and HSTS · CORS · secret scanning",
    "cv_s5_k": "Development",
    "cv_s5_v": "Python (FastAPI, SQLAlchemy, Pydantic) · TypeScript (Next.js, React) · REST APIs · pytest",
    "cv_s6_k": "Databases",
    "cv_s6_v": "PostgreSQL · MySQL · SQL · relational modeling",
    "cv_infra_title": "Infrastructure and operations",
    "cv_infra_note": "— my own servers, 2026",
    "cv_infra_1": "I administer Ubuntu servers on AWS EC2: SSH access, users and permissions, updates with apt and a UFW firewall.",
    "cv_infra_2": "I manage services with systemd and Docker Compose, and troubleshoot failures by reviewing logs with journalctl and from containers.",
    "cv_infra_3": "I set up Caddy as a reverse proxy with HTTPS, and deployments with a prior database backup and automatic migrations.",
    "cv_projects_title": "Projects",
    "cv_live": "— In production",
    "cv_code": "Code",
    "cv_p1_text": "Data quality web platform for ecommerce and logistics: it detects orders and shipments with errors or anomalous values and turns them into incidents with an owner and a deadline.",
    "cv_p1_b1": "Built a REST API with more than 50 endpoints, with local and Google authentication, roles and user auditing.",
    "cv_p1_b2": "Implemented a validation rules and anomaly detection engine, with a tracking dashboard in Next.js.",
    "cv_p1_b3": "Isolated the public demo from the real data with deny-by-default access; 226 automated tests.",
    "cv_p2_text": "Appointment management web system for barbershops, with client, barber and administrator roles. It replaces manual coordination, which causes overlaps: the server computes free slots from services and absences.",
    "cv_p2_b1": "Implemented server-side authorization: identity comes from the token and prevents acting on another user's data.",
    "cv_p2_b2": "Guaranteed integrity under simultaneous bookings with a PostgreSQL exclusion constraint.",
    "cv_p2_b3": "Isolated public demo with expiration and quotas; 143 automated tests.",
    "cv_p3_text": "Stock, sales, purchasing, customer and supplier management for small stores, rebuilt as a web application from a desktop version. It replaces separate spreadsheets and keeps a trace of every movement.",
    "cv_p3_b1": "Built a point of sale with barcode scanning and PDF receipts, expiration dates, purchasing, reports and three roles.",
    "cv_p3_b2": "Stock operations in transactions with row locking; totals computed on the server and history without deletion.",
    "cv_p3_b3": "Sessions in HttpOnly cookies with real invalidation, bcrypt passwords and restricted CORS.",
    "cv_education_title": "Education",
    "cv_edu1_title": "Software Development technical degree",
    "cv_edu1_meta": "Terciario Urquiza, Rosario · final year in progress · 2024 – present",
    "cv_edu2_meta": "Cisco Networking Academy and NDG · completed, September 2026",
    "cv_edu2_verify": "Verify credential",
    "cv_edu3_meta": "Cisco Networking Academy · in progress · 4 courses: networking, addressing, troubleshooting and security",
    "cv_experience_title": "Work experience",
    "cv_exp1_title": "Sales and customer service",
    "cv_exp1_meta": "KINGU, Rosario · 03/2025 – 11/2025",
    "cv_exp1_text": "Customer service, till and payment terminals, stock control.",
    "cv_exp2_title": "Sales and stock control",
    "cv_exp2_meta": "Almacén Tina, Rosario · 02/2024 – 12/2024",
    "cv_exp2_text": "Restocking, inventory records and payments.",
    "cv_exp3_title": "Administrative internship",
    "cv_exp3_meta": "S.I.S.O SRL, Rosario · 11/2023 – 12/2023",
    "cv_exp3_text": "Data entry and correction in accounting software.",
    "cv_other_title": "Languages and other details",
    "cv_other_1": "Spanish, native",
    "cv_other_2": "English, advanced",
    "cv_other_3": "Driver's license B1 with own vehicle",
    "cv_other_4": "Microsoft 365 and Excel",
    "cv_other_5": "Customer service"
  }
};
