/* Traducciones de la pagina de CV. Mismo formato que i18n-data.js. */
window.PF_TRANSLATIONS = {
  "es": {
    "lang_aria": "Switch to English",
    "cv_back": "← Portfolio",
    "cv_pdf": "Descargar PDF",
    "cv_photo_alt": "Retrato de Aaron Brumat",
    "cv_role": "Software Developer — Backend, APIs y datos",
    "cv_summary": "Estudiante del último año de Técnico Desarrollador de Software. Construyo aplicaciones completas con Python y TypeScript, y llevo cada proyecto hasta dejarlo desplegado y probado.",
    "cv_c_email": "Email",
    "cv_c_phone": "Teléfono",
    "cv_c_loc": "Ubicación",
    "cv_c_loc_value": "Rosario, Santa Fe, Argentina",
    "cv_profile_title": "Perfil",
    "cv_profile_text": "Trabajo sobre todo con Python y SQL: APIs REST con FastAPI, modelos de datos en PostgreSQL y MySQL, y frontends en Next.js y TypeScript. Me interesan el backend, el modelado de datos y el despliegue; estoy orientando esa base hacia Data Engineering, Machine Learning e IA aplicada, y hacia la administración de servidores: infraestructura Linux y redes. Busco sumarme a un equipo de desarrollo donde pueda aportar y seguir creciendo.",
    "cv_projects_title": "Proyectos",
    "cv_p1_meta": "Full-stack · en producción · 2026",
    "cv_p1_text": "Plataforma de monitoreo de calidad de datos para ecommerce y logística. Un motor de reglas por dominio valida cada dataset, puntúa su calidad, detecta anomalías por z-score modificado sobre mediana y MAD, y convierte los hallazgos en incidencias con severidad, responsable y SLA. Incluye autenticación local y con Google, roles, exportes y un sandbox público temporal y aislado para probarla sin cuenta.",
    "cv_p1_b1": "Backend FastAPI con SQLAlchemy y Pydantic sobre PostgreSQL, más de 50 endpoints REST y migraciones Alembic.",
    "cv_p1_b2": "226 tests de pytest: aislamiento entre sesiones, cuotas, validación de esquemas y métricas del dashboard.",
    "cv_p1_b3": "Frontend Next.js con React, TypeScript, Tailwind y Recharts.",
    "cv_p1_b4": "Despliegue con Docker Compose en EC2 (Ubuntu) detrás de Caddy, y frontend en Cloudflare.",
    "cv_p2_meta": "Aplicación de escritorio · 2026",
    "cv_p2_text": "Sistema de gestión de stock, ventas, clientes y proveedores en Python sobre MySQL. ABM completo con validaciones, ventas que descuentan stock y bloquean la operación si no alcanza, historial de movimientos y reportes exportables a CSV y PDF. Acceso con contraseña hasheada con bcrypt o inicio de sesión con Google, y esquema versionado con migraciones SQL.",
    "cv_skills_title": "Habilidades técnicas",
    "cv_s1_k": "Lenguajes",
    "cv_s1_v": "Python, TypeScript, JavaScript, SQL, HTML, CSS",
    "cv_s2_k": "Backend",
    "cv_s2_v": "FastAPI, SQLAlchemy, Pydantic, Alembic, REST, JWT, OAuth 2.0, pytest",
    "cv_s3_k": "Datos",
    "cv_s3_v": "PostgreSQL, MySQL, modelado relacional, migraciones, validación de esquemas",
    "cv_s4_k": "Frontend",
    "cv_s4_v": "Next.js, React, Tailwind CSS, Recharts",
    "cv_s5_k": "Infraestructura",
    "cv_s5_v": "Docker, Docker Compose, Linux (Ubuntu), AWS EC2, Caddy, Cloudflare, Git",
    "cv_s6_k": "Aprendiendo",
    "cv_s6_v": "Data Engineering, Machine Learning, IA aplicada, pandas, administración de servidores, infraestructura Linux y redes",
    "cv_s7_k": "Cursada",
    "cv_s7_v": "C#, Django, Flask",
    "cv_soft_title": "Complementarias",
    "cv_soft_1": "Resolución de problemas y atención al detalle",
    "cv_soft_2": "Responsabilidad y adaptabilidad",
    "cv_soft_3": "Atención al cliente y trabajo en equipo",
    "cv_soft_4": "Microsoft 365",
    "cv_lang_title": "Idiomas",
    "cv_lang_1": "Español — nativo",
    "cv_lang_2": "Inglés — intermedio",
    "cv_lang_3": "Portugués — básico",
    "cv_education_title": "Educación",
    "cv_edu1_title": "Técnico Desarrollador de Software",
    "cv_edu1_meta": "Terciario Urquiza, Rosario · 2024 — en curso (último año)",
    "cv_edu2_title": "Secundaria completa",
    "cv_edu2_meta": "María Bicecci, Rosario · 2019 — 2023",
    "cv_edu3_title": "Certificado de Iniciación al Desarrollo con IA",
    "cv_edu3_meta": "BIG school · marzo 2026 · 6 horas",
    "cv_experience_title": "Experiencia laboral",
    "cv_experience_note": "Fuera de IT. Procesos, registros y responsabilidad diaria.",
    "cv_exp1_title": "Vendedor y atención al cliente",
    "cv_exp1_meta": "Local de ropa KINGU · 03/2025 — 11/2025",
    "cv_exp1_text": "Atención personalizada, manejo de caja, cobros y cierres.",
    "cv_exp2_title": "Vendedor y control de stock",
    "cv_exp2_meta": "Almacén Tina · 02/2024 — 12/2024",
    "cv_exp2_text": "Control de mercadería y registro de existencias.",
    "cv_exp3_title": "Pasantía administrativa",
    "cv_exp3_meta": "S.I.S.O SRL · 11/2023 — 12/2023",
    "cv_exp3_text": "Carga y corrección de datos en software contable.",
    "cv_availability_title": "Disponibilidad",
    "cv_availability_text": "Full time, de lunes a sábado. Disponible para trabajo presencial en Rosario, híbrido o remoto."
  },
  "en": {
    "lang_aria": "Cambiar a espanol",
    "cv_back": "← Portfolio",
    "cv_pdf": "Download PDF",
    "cv_photo_alt": "Portrait of Aaron Brumat",
    "cv_role": "Software Developer — Backend, APIs and data",
    "cv_summary": "Final-year student of a Software Development technical degree. I build complete applications with Python and TypeScript, and take every project all the way to deployed and tested.",
    "cv_c_email": "Email",
    "cv_c_phone": "Phone",
    "cv_c_loc": "Location",
    "cv_c_loc_value": "Rosario, Santa Fe, Argentina",
    "cv_profile_title": "Profile",
    "cv_profile_text": "I work mostly with Python and SQL: REST APIs with FastAPI, data models in PostgreSQL and MySQL, and frontends in Next.js and TypeScript. I am drawn to backend work, data modelling and deployment, and I am pointing that foundation towards Data Engineering, Machine Learning and applied AI, and towards server administration: Linux infrastructure and networking. I am looking to join a development team where I can contribute and keep growing.",
    "cv_projects_title": "Projects",
    "cv_p1_meta": "Full-stack · in production · 2026",
    "cv_p1_text": "A data quality monitoring platform for ecommerce and logistics. A domain rule engine validates each dataset, scores its quality, detects anomalies via a modified z-score over median and MAD, and turns findings into incidents with severity, owner and SLA. It includes local and Google authentication, roles, exports and a temporary, isolated public sandbox so anyone can try it without an account.",
    "cv_p1_b1": "FastAPI backend with SQLAlchemy and Pydantic on PostgreSQL, over 50 REST endpoints and Alembic migrations.",
    "cv_p1_b2": "226 pytest tests: cross-session isolation, quotas, schema validation and dashboard metrics.",
    "cv_p1_b3": "Next.js frontend with React, TypeScript, Tailwind and Recharts.",
    "cv_p1_b4": "Deployed with Docker Compose on EC2 (Ubuntu) behind Caddy, frontend on Cloudflare.",
    "cv_p2_meta": "Desktop application · 2026",
    "cv_p2_text": "Stock, sales, customer and supplier management in Python on MySQL. Full CRUD with validation, sales that draw down stock and block the operation when it is not enough, movement history and reports exportable to CSV and PDF. Access with a bcrypt-hashed password or Google sign-in, and a versioned schema with SQL migrations.",
    "cv_skills_title": "Technical skills",
    "cv_s1_k": "Languages",
    "cv_s1_v": "Python, TypeScript, JavaScript, SQL, HTML, CSS",
    "cv_s2_k": "Backend",
    "cv_s2_v": "FastAPI, SQLAlchemy, Pydantic, Alembic, REST, JWT, OAuth 2.0, pytest",
    "cv_s3_k": "Data",
    "cv_s3_v": "PostgreSQL, MySQL, relational modelling, migrations, schema validation",
    "cv_s4_k": "Frontend",
    "cv_s4_v": "Next.js, React, Tailwind CSS, Recharts",
    "cv_s5_k": "Infrastructure",
    "cv_s5_v": "Docker, Docker Compose, Linux (Ubuntu), AWS EC2, Caddy, Cloudflare, Git",
    "cv_s6_k": "Learning",
    "cv_s6_v": "Data Engineering, Machine Learning, applied AI, pandas, server administration, Linux infrastructure and networking",
    "cv_s7_k": "Coursework",
    "cv_s7_v": "C#, Django, Flask",
    "cv_soft_title": "Additional",
    "cv_soft_1": "Problem solving and attention to detail",
    "cv_soft_2": "Accountability and adaptability",
    "cv_soft_3": "Customer service and teamwork",
    "cv_soft_4": "Microsoft 365",
    "cv_lang_title": "Languages",
    "cv_lang_1": "Spanish — native",
    "cv_lang_2": "English — intermediate",
    "cv_lang_3": "Portuguese — basic",
    "cv_education_title": "Education",
    "cv_edu1_title": "Software Development (technical degree)",
    "cv_edu1_meta": "Terciario Urquiza, Rosario · 2024 — in progress (final year)",
    "cv_edu2_title": "Secondary school completed",
    "cv_edu2_meta": "Maria Bicecci, Rosario · 2019 — 2023",
    "cv_edu3_title": "Certificate of Introduction to Development with AI",
    "cv_edu3_meta": "BIG school · March 2026 · 6 hours",
    "cv_experience_title": "Work experience",
    "cv_experience_note": "Outside IT. Processes, records and daily accountability.",
    "cv_exp1_title": "Sales assistant and customer service",
    "cv_exp1_meta": "KINGU clothing store · 03/2025 — 11/2025",
    "cv_exp1_text": "Personalised service, register handling, payments and closings.",
    "cv_exp2_title": "Sales assistant and stock control",
    "cv_exp2_meta": "Almacen Tina · 02/2024 — 12/2024",
    "cv_exp2_text": "Merchandise control and inventory records.",
    "cv_exp3_title": "Administrative internship",
    "cv_exp3_meta": "S.I.S.O SRL · 11/2023 — 12/2023",
    "cv_exp3_text": "Data entry and correction in accounting software.",
    "cv_availability_title": "Availability",
    "cv_availability_text": "Full time, Monday to Saturday. Open to on-site work in Rosario, hybrid or remote."
  }
};
